name: ${PROJECT_NAME}

services:

  loki:
    image: grafana/loki
    container_name: ${LOKI_CONTAINER_NAME}
    env_file: .env
    volumes:
      - ./configs/loki-config.yaml:/mnt/config/loki-config.yaml
    ports:
      # - ${LOKI_PORT}:${LOKI_PORT}
      - "3100:3100"
    command:
      - -config.file=/mnt/config/loki-config.yaml


  grafana:
    image: grafana/grafana
    container_name: ${GRAFANA_CONTAINER_NAME}
    env_file: .env
    volumes:
      - ./configs/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yml
    ports:
      - ${GRAFANA_PORT}:${GRAFANA_PORT}
    depends_on:
      - loki

  promtail:
    image: grafana/promtail
    container_name: ${PROMTAIL_CONTAINER_NAME}
    env_file: .env
    volumes:
      - ./configs/promtail-config.yaml:/mnt/config/promtail-config.yaml
      - /var/log:/var/log
    ports:
      - ${PROMTAIL_PORT}:${PROMTAIL_PORT}
    depends_on:
      - loki
    command: -config.file=/mnt/config/promtail-config.yaml
